import type { Metadata } from 'next';
import { Nunito, Nunito_Sans } from 'next/font/google';
import './globals.css';
import GlobalHeader from '@/components/header';
import { ThemeProvider } from '@/components/theme-provider';

const getNunitoSans = Nunito_Sans({
  variable: '--font-nunito-sans',
  subsets: ['latin'],
});

const getNunito = Nunito({
  variable: '--font-nunito',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${getNunito.variable} ${getNunitoSans.variable} antialiased font-nunito-sans font-nunito `}>
        <ThemeProvider attribute="class" defaultTheme="light" enableSystem disableTransitionOnChange>
          <main>
            <section>
              <GlobalHeader />
            </section>
            <section>{children}</section>
            <section>Footer</section>
          </main>
        </ThemeProvider>
      </body>
    </html>
  );
}
